# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            DataSorcery
tagline:          Quando a razão encontra...
url:              http://blog.datasorcery.io
paginate:         1
baseurl:          /
author:
  name:           Fábio Franco Costa
  url:            https://twitter.com/costa_2_0
  email:          fabio@datasorcery.io

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:
  Sobre: '/sobre'
  Arquivo: '/arquivo'
  Feed: '/atom.xml'
